In [6]:


import numpy as np
array1 = np.array([range(10)])
print(f'1D array : {array1}')


1D array : [[0 1 2 3 4 5 6 7 8 9]]


In [19]:
# 1. A 1D array of numbers from 0 to 9
array1 = np.array([range(10)])
print(f'1D array : {array1}')

# 2. A 2D array of shape (3, 4) filled with zeros
array2 = np.zeros((3, 4))
print(f'3x4 array of Zero values : \n{array2}')

# 3. A 3x3 identity matrix
array3 = np.eye(3)
print(f'3x3 Identity matrix : \n{array3}')

# 4. A 1D array of 10 equally spaced values between 1 and 100
array4 = np.linspace(1, 100, 10)
print(f'1D array of 10 equally spaced values between 1 and 100 : \n{array4}')

# 5. A 3x3 array with random integers between 10 and 50
array5 = np.random.randint(10, 51, size=(3, 3))
print(f'3x3 array with random integers between 10 and 50 : \n{array5}')




1D array : [[0 1 2 3 4 5 6 7 8 9]]
3x4 array of Zero values : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3x3 Identity matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1D array of 10 equally spaced values between 1 and 100 : 
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
3x3 array with random integers between 10 and 50 : 
[[21 41 48]
 [11 46 38]
 [48 24 33]]


In [33]:

# Create a 3D array with shape (2, 3, 4) using random numbers
#array6 = np.random.randint(10, 51, size=(2, 3, 4))
array6 = np.random.randn(2, 3, 4)

print(f'3D array with shape (2, 3, 4) : \n{array6}')

# Find and print:
# - Number of dimensions
# - Shape of the array
# - Total number of elements
# - Data type of elements
# - Size in bytes of each element
# - Total memory consumed by the array
print(f'Number of dimensions: {array6.ndim}')
print(f'Shape of the array: {array6.shape}')
print(f'Total number of elements: {array6.size}')
print(f'Data type of elements: {array6.dtype}')
print(f'Size in bytes of each element: {array6.itemsize}')
print(f'Total memory consumed by the array: {array6.nbytes} bytes')


3D array with shape (2, 3, 4) : 
[[[ 1.79741981  1.18648742  1.1439328  -0.01559609]
  [ 1.55173866  0.12834009  0.40457903 -1.51676646]
  [ 0.35680676  0.2788823  -1.22803166  1.24313082]]

 [[-0.07735101  0.00383222  0.29463982 -0.467492  ]
  [ 0.98455457 -1.49103773 -0.7247919  -1.24885978]
  [ 0.75222738  0.0518259  -0.98238196  1.83217741]]]
Number of dimensions: 3
Shape of the array: (2, 3, 4)
Total number of elements: 24
Data type of elements: float64
Size in bytes of each element: 8
Total memory consumed by the array: 192 bytes


In [36]:
# Exercise 3: 
# Create a 1D array of numbers from 1 to 20
# Perform the following operations:
# - Access the first, last, and middle elements
# - Slice the array to get elements from index 5 to 15
# - Get all even numbers using slicing
# - Reverse the array using slicing

array7 = np.array(range(1, 21))
print(f'Original array: {array7}')
print(f'First element: {array7[0]}')
print(f'Last element: {array7[-1]}')
print(f'Middle element: {array7[len(array7)//2]}')
print(f'Elements from index 5 to 15: {array7[5:16]}')
print(f'All even numbers: {array7[array7 % 2 == 0]}')
print(f'Reversed array: {array7[::-1]}')


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First element: 1
Last element: 20
Middle element: 11
Elements from index 5 to 15: [ 6  7  8  9 10 11 12 13 14 15 16]
All even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Reversed array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [53]:
# Exercise 4: 
# Create a 5x5 array with numbers from 1 to 25
# Perform the following tasks:
# - Access the element at row 2, column 3
# - Extract the third row and second column
# - Slice a 3x3 sub-matrix from the center
# - Replace all values in the last row with 0
# - Change the first column to all -1
array8 = np.array(range(1, 26)).reshape(5, 5)
print(f'Original 5x5 array: \n{array8}')
print(f'Element at row 2, column 3: {array8[1, 2]}')
print(f'Third row: {array8[2, :]}')
print(f'Second column: {array8[:, 1]}')
print(f'3x3 sub-matrix from the center: \n{array8[1:4, 1:4]}')
array8[-1, :] = 0
print(f'Array after replacing last row with 0: \n{array8}')
array8[:, 0] = -1
print(f'Array after changing first column to -1: \n{array8}')

  

Original 5x5 array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Element at row 2, column 3: 8
Third row: [11 12 13 14 15]
Second column: [ 2  7 12 17 22]
3x3 sub-matrix from the center: 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Array after replacing last row with 0: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  0  0  0  0]]
Array after changing first column to -1: 
[[-1  2  3  4  5]
 [-1  7  8  9 10]
 [-1 12 13 14 15]
 [-1 17 18 19 20]
 [-1  0  0  0  0]]


In [55]:
# Exercise 5: 
# Create a 1D array of 15 random integers between 1 and 50
# Perform the following:
# - Select elements at indices [1, 3, 5, 7]
# - Find all elements greater than 25
# - Replace all values less than 10 with 10
# - Count how many values are between 20 and 40 (inclusive)
# - Extract only the odd numbers from the array

array9 = np.random.randint(1, 51, size=15)
print(f'Original array: {array9}')
print(f'Elements at indices [1, 3, 5, 7]: {array9[[1, 3, 5, 7]]}')
print(f'Elements greater than 25: {array9[array9 > 25]}')
array9[array9 < 10] = 10
print(f'Array after replacing values less than 10 with 10: {array9}')
count_20_40 = np.sum((array9 >= 20) & (array9 <= 40))
print(f'Count of values between 20 and 40 (inclusive): {count_20_40}')
# - Extract only the odd numbers from the array
odd_numbers = array9[array9 % 2 != 0]
print(f'Odd numbers in the array: {odd_numbers}')


Original array: [ 1 16 29  7  7 22  1 29 10 26 14 22 25 28  1]
Elements at indices [1, 3, 5, 7]: [16  7 22 29]
Elements greater than 25: [29 29 26 28]
Array after replacing values less than 10 with 10: [10 16 29 10 10 22 10 29 10 26 14 22 25 28 10]
Count of values between 20 and 40 (inclusive): 7
Odd numbers in the array: [29 29 25]
